Toy_PJT/Django/덕몽어스 실시간 반영 웹/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/<str:target>/plus/', views.plus, name='plus'),
    path('<int:user_pk>/<str:target>/minus/', views.minus, name='minus'),
    path('<int:user_pk>/<str:target>/reset/', views.reset, name='reset'),
]

Toy_PJT/Django/덕몽어스 실시간 반영 웹/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Toy_PJT/Django/덕몽어스 실시간 반영 웹/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    image = models.ImageField(blank=True)
    win_cnt = models.BigIntegerField()
    lose_cnt = models.BigIntegerField()
    kill_cnt = models.BigIntegerField()
    pass

Toy_PJT/Django/덕몽어스 실시간 반영 웹/accounts/forms.py
from email.mime import image
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = 'username', 'password1', 'password2', 'image'

Toy_PJT/Django/덕몽어스 실시간 반영 웹/accounts/views.py
from django.http.response import JsonResponse
from django.contrib.auth import get_user_model
from django.contrib.auth import login as user_login
from django.contrib.auth import logout as user_logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from .forms import CustomUserCreationForm
from .models import User
 
# Create your views here.
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person':person
    }
    return render(request, 'accounts/profile.html', context)

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.win_cnt, user.lose_cnt, user.kill_cnt = 0, 0, 0
            user.save()
            user_login(request, user)
            return redirect('accounts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user_login(request, form.get_user())
            return redirect('accounts:index')            
    else:
        form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    user_logout(request)
    return redirect('accounts:index')

def index(request):
    users = get_list_or_404(get_user_model())
    context = {
        'users':users
    }
    return render(request, 'accounts/index.html', context)

def follow(request, user_pk):
    if request.user.is_authenticated:
        me = request.user
        you = get_object_or_404(get_user_model(), pk=user_pk)
        if me != you:
            if you.followings.filter(pk=me.pk).exists():
                you.followings.remove(me)
                is_liked = False
            else:
                you.followings.add(me)
                is_liked = True
            context = {
                'is_liked': is_liked
            }
            return JsonResponse(context)
        return redirect('accounts:profile', you.username)
    return redirect('accounts:login')

def plus(request, user_pk, target):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    if target == 'win':
        person.win_cnt += 1
    elif target == 'lose':
        person.lose_cnt += 1
    else:
        person.kill_cnt += 1
    person.save()
    return redirect('accounts:profile', person.username)

def minus(request, user_pk, target):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    if target == 'win':
        if person.win_cnt:
            person.win_cnt -= 1
    elif target == 'lose':
        if person.lose_cnt:
            person.lose_cnt -= 1
    else:
        if person.kill_cnt:
            person.kill_cnt -= 1
    person.save()
    return redirect('accounts:profile', person.username)

def reset(request, user_pk, target):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    if target == 'win':
        if person.win_cnt:
            person.win_cnt = 0
    elif target == 'lose':
        if person.lose_cnt:
            person.lose_cnt = 0
    else:
        if person.kill_cnt:
            person.kill_cnt = 0
    person.save()
    return redirect('accounts:profile', person.username)

Toy_PJT/Django/덕몽어스 실시간 반영 웹/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="m-auto d-flex row container">
    {% if users %}
    {% for u in users %}
    {% if not u.is_superuser %}
    <div class="card m-5 rounded-3 p-0 border border-warning border-5" style="width: 18rem;">
        <img src="{{ u.image.url }}" class="card-img-top rounded-5 w-100 h-100" alt="{{ u}}의 기본 이미지">
        <div class="card-body">
            <a class="text-decoration-none text-dark btn btn-warning w-100" href="{% url 'accounts:profile' u.username%}"><b class="card-title">{{ u }}</b></a>
            <hr>
            <div class="d-flex flex-column align-items-around">
                <p class="my-2">팔로워 : {{ u.followers.all|length }}명</p>
                <p class="my-2">팔로잉 : {{ u.followings.count }}명</p>
            </div>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex">
                <p class="col-2 my-2">승리</p>
                <p class="col-1 my-2"> : </p>
                <p class="col-1 my-2">{{ u.win_cnt }}</p>
            </li>
            <li class="list-group-item d-flex">
                <p class="col-2 my-2">패배</p>
                <p class="col-1 my-2"> : </p>
                <p class="col-1 my-2">{{ u.lose_cnt }}</p>
            </li>
            <li class="list-group-item d-flex">
                <p class="col-2 my-2">킬</p>
                <p class="col-1 my-2"> : </p>
                <p class="col-1 my-2">{{ u.kill_cnt }}</p>
            </li>
        </ul>
    </div>
    {% endif %}
    {% endfor %}
    {% else %}
    <h3>현재 유저가 없습니다.</h3>
    {% endif %}
</div>
<nav class="nav flex-column position-fixed end-0 top-50 translate-middle">
    <ol class="form-control text-center m-0 border border-danger border-5 rounded-0"><b>Ranking</b></ol>
    {% for u in users|dictsortreversed:"win_cnt" %}
        {% if not u.is_superuser %}
            <li>
                <a class="form-control text-decoration-none text-center rounded-0" href="{% url 'accounts:profile' u.username %}">
                    {{ forloop.counter }}위 {{ u.username }}({{ u.win_cnt }}점)
                </a>
            </li>
        {% endif %}
    {% endfor %}
</nav>
{% endblock content %}

Toy_PJT/Django/덕몽어스 실시간 반영 웹/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    <p>{{ form.as_p }}</p>
    <input class="btn btn-warning" type="submit" value="로그인">
    <a class="btn btn-warning" href="{% url 'accounts:index' %}">뒤로가기</a>
</form>
{% endblock content %}

Toy_PJT/Django/덕몽어스 실시간 반영 웹/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column">
<div class="card m-5" style="width: 18rem;">
    <img src="{{ person.image.url }}" class="card-img-top" alt="{{ person }}의 기본 이미지">
    <div class="card-body">
        <b class="btn btn-warning card-title w-100"><b>{{ person }}</b></b>
        <hr>
        <div class="d-flex align-items-center justify-content-around">
            <div class="d-flex flex-column">
                <p class="my-2">팔로워 : {{ person.followers.all|length }}명</p>
                <p class="my-2">팔로잉 : {{ person.followings.count }}명</p>
            </div>
            <form action="{% url 'accounts:follow' person.pk %}" method="POST">
                {% csrf_token %}
                {% if person != user %}
                {% if request.user in person.followings.all %}
                <input class="btn btn-warning" type="submit" value="팔로우 해제" id="unfollow">
                {% else %}
                <input class="btn btn-warning" type="submit" value="팔로우" id="follow">
                {% endif %}
                {% endif %}
            </form>
        </div>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex">
            <p class="col-2 my-2">승리</p>
            <p class="col-1 my-2"> : </p>
            <p class="col-1 my-2">{{ person.win_cnt }}</p>
            {% if person == user or user.is_superuser %}
            <a class="btn btn-info ms-2" style="width:40px; height:40px;" href="{% url 'accounts:plus' person.pk "win" %}">+</a>
            <a class="btn btn-danger ms-2" style="width:40px; height:40px;" href="{% url 'accounts:minus' person.pk "win" %}">-</a>
            <a class="btn btn-warning ms-2" style="width:40px; height:40px;" href="{% url 'accounts:reset' person.pk "win" %}">c</a>
            {% endif %}
        </li>
        <li class="list-group-item d-flex">
            <p class="col-2 my-2">패배</p>
            <p class="col-1 my-2"> : </p>
            <p class="col-1 my-2">{{ person.lose_cnt }}</p>
            {% if person == user or user.is_superuser %}
            <a class="btn btn-info ms-2" style="width:40px; height:40px;" href="{% url 'accounts:plus' person.pk "lose" %}">+</a>
            <a class="btn btn-danger ms-2" style="width:40px; height:40px;" href="{% url 'accounts:minus' person.pk "lose" %}">-</a>
            <a class="btn btn-warning ms-2" style="width:40px; height:40px;" href="{% url 'accounts:reset' person.pk "lose" %}">c</a>
            {% endif %}
        </li>
        <li class="list-group-item d-flex">
            <p class="col-2 my-2">킬</p>
            <p class="col-1 my-2"> : </p>
            <p class="col-1 my-2">{{ person.kill_cnt }}</p>
            {% if person == user or user.is_superuser %}
            <a class="btn btn-info ms-2" style="width:40px; height:40px;" href="{% url 'accounts:plus' person.pk "kill" %}">+</a>
            <a class="btn btn-danger ms-2" style="width:40px; height:40px;" href="{% url 'accounts:minus' person.pk "kill" %}">-</a>
            <a class="btn btn-warning ms-2" style="width:40px; height:40px;" href="{% url 'accounts:reset' person.pk "kill" %}">c</a>
            {% endif %}
        </li>
    </ul>
</div>
<a class="btn btn-warning" href="{% url 'accounts:index' %}">뒤로가기</a>
</div>
{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    const forms = document.querySelector
</script>
{% endblock script %}
{% endblock content %}

Toy_PJT/Django/덕몽어스 실시간 반영 웹/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'accounts:signup' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-control my-3">
    {% for f in form %}
    {% if f.name == 'username' %}
        <div class="d-flex">
            <p class="col-5">이름</p>
            <p class="col-5">{{ f }}</p><hr>
        </div>
        {% elif f.name == 'password1' %}
        <div class="d-flex">
            <p class="col-5">비밀번호</p>
            <p class="col-5">{{ f }}</p><hr>
        </div>
        {% elif f.name == 'password2' %}
        <div class="d-flex">
            <p class="col-5">비밀번호 확인</p>
            <p class="col-5">{{ f }}</p><hr>
        </div>
        {% else %}
        <div class="d-flex">
            <p class="col-5">이미지 선택</p>
            <p class="col-5">{{ f }}</p><hr>
        </div>
    </div>
    {% endif %}
    {% endfor %}
    <div>
        <input class="btn btn-warning" type="submit" value="회원가입">
        <a class="btn btn-warning" href="{% url 'accounts:index' %}">뒤로가기</a>
    </div>
</form>    

{% endblock content %}

Toy_PJT/Django/덕몽어스 실시간 반영 웹/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">  <title>Document</title>
</head>
<body>
    <div class="nav bg-warning p-2">
        <a class="btn m-auto border-primary border border-5 rounded-5" href="{% url 'accounts:index' %}">
            <h1 class="text-primary p-0">
                <b class="m-auto">No Duck Goose!</b>
            </h1>
        </a>
    </div>
    {% if user.is_authenticated %}
    <div class="nav bg-white border-bottom border-warning">
        <h5 class="p-2 m-2 px-5">
            <b>{{ user }}님, 환영합니다!</b>
        </h5>
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input class="btn btn-warning m-2" type="submit" value="로그아웃">
        </form>
    </div>
    {% else %}
    <div class="nav bg-white border-bottom border-dark">
        <h5 class="p-2 m-2 px-5">
            <b>방문자님, 환영합니다!</b>
        </h5>
        <a class="btn btn-warning m-2" href="{% url 'accounts:login' %}">로그인</a> 
        <a class="btn btn-warning m-2" href="{% url 'accounts:signup' %}">회원가입</a> 
    </div>
    {% endif %}
    <div class="d-flex justify-content-center">
    {% block content %}
    
    {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    {% block script %}
        
    {% endblock script %}
</body>
</html>